{{- with .Values.deployments.keycloak }}

# Keycloak Realm ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release: {{ $.Release.Name }}
    app.kubernetes.io/revision: '{{ $.Release.Revision }}'
data:
  camel-realm.json: |-
    {{- $.Files.Get "etc/camel-realm.json" | nindent 4 }}

# Keycloak Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release: {{ $.Release.Name }}
    app.kubernetes.io/revision: '{{ $.Release.Revision }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/release: {{ $.Release.Name }}
        app.kubernetes.io/revision: '{{ $.Release.Revision }}'
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:{{ .version }}
          args:
            - "start-dev"
            - "--import-realm"
            - "--http-enabled=true"
            - "--http-relative-path=/kc"
            - "--proxy-headers=xforwarded"
            - "--proxy-protocol-enabled=false"
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-realm-config
              mountPath: /opt/keycloak/data/import
              readOnly: true
      volumes:
        - name: keycloak-realm-config
          configMap:
            name: keycloak-realm-config

# Keycloak Service
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app.kubernetes.io/name: keycloak

# Keycloak Ingress Insecure
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-http
  labels:
    app.kubernetes.io/name: keycloak-http
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/kc`)
      kind: Rule
      services:
        - name: keycloak
          port: 8080

# Keycloak Ingress Secure
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-https
  labels:
    app.kubernetes.io/name: keycloak-https
spec:
  entryPoints:
      - websecure
  routes:
    - match: PathPrefix(`/kc`)
      kind: Rule
      services:
        - name: keycloak
          port: 8080
  tls:
    secretName: traefik-tls
---
{{- end }}
