{{- with .Values.deployments.whoami }}

# Whoami Deployment
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80

# Whoami Service
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: whoami

# Whoami IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/who`)
      kind: Rule
      services:
        - name: whoami
          port: 80
      middlewares:
        - name: strip-prefix-who
  tls:
    secretName: traefik-tls

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-who
  labels:
    app.kubernetes.io/name: whoami
spec:
  stripPrefix:
    prefixes:
      - /who
---
{{- end }}

