apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kafka-oauth
    app.kubernetes.io/runtime: camel
  name: kafka-oauth
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-oauth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-oauth
    spec:
      containers:
      - image: examples/kafka-oauth:1.0.0
        name: kafka-oauth
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
