
# Artemis StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: artemis
  labels:
    app.kubernetes.io/name: artemis
spec:
  serviceName: artemis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: artemis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: artemis
    spec:
      containers:
        - name: artemis
          image: quay.io/artemiscloud/activemq-artemis-broker:artemis.2.38.0
          env:
            - name: AMQ_USER
              value: admin
            - name: AMQ_PASSWORD
              value: admin
          ports:
            - containerPort: 61616
            - containerPort: 8161
          volumeMounts:
            - name: broker-config
              mountPath: /var/lib/artemis-instance/etc-override/broker.xml
              subPath: broker.xml
      volumes:
        - name: broker-config
          configMap:
            name: artemis-config
---
# Artemis Service
apiVersion: v1
kind: Service
metadata:
  name: artemis
  labels:
    app.kubernetes.io/name: artemis
spec:
  type: NodePort
  ports:
    - port: 61616
      nodePort: 30616
  selector:
    app.kubernetes.io/name: artemis

---
# Artemis Console Service
apiVersion: v1
kind: Service
metadata:
  name: artemis-console
  labels:
    app.kubernetes.io/name: artemis
spec:
  type: NodePort
  ports:
    - port: 8161
      nodePort: 30816
  selector:
    app.kubernetes.io/name: artemis
