{{- with .Values.deployments.keycloak }}

# Keycloak Realm ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release: {{ $.Release.Name }}
    app.kubernetes.io/revision: '{{ $.Release.Revision }}'
data:
  demo-realm.json: |-
    {{- $.Files.Get "etc/camel-realm.json" | nindent 4 }}

# Keycloak TLS Secret
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-tls
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release: {{ $.Release.Name }}
    app.kubernetes.io/revision: '{{ $.Release.Revision }}'
type: kubernetes.io/tls
data:
  tls.crt: {{ $.Files.Get "etc/keycloak.crt" | b64enc }}
  tls.key: {{ $.Files.Get "etc/keycloak.key" | b64enc }}

# Keycloak Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/release: {{ $.Release.Name }}
    app.kubernetes.io/revision: '{{ $.Release.Revision }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/release: {{ $.Release.Name }}
        app.kubernetes.io/revision: '{{ $.Release.Revision }}'
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.2
          args:
            - "start-dev"
            - "--https-port=8443"
            - "--https-certificate-file=/etc/x509/https/tls.crt"
            - "--https-certificate-key-file=/etc/x509/https/tls.key"
            - "--import-realm"
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
          ports:
            - containerPort: 8080
            - containerPort: 8443
          volumeMounts:
            - name: keycloak-tls
              mountPath: /etc/x509/https
              readOnly: true
            - name: keycloak-realm-config
              mountPath: /opt/keycloak/data/import
              readOnly: true
      volumes:
        - name: keycloak-tls
          secret:
            secretName: keycloak-tls
        - name: keycloak-realm-config
          configMap:
            name: keycloak-realm-config

# Keycloak Service
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: {{ .nodePortHttp }}
    - name: https
      port: 8443
      nodePort: {{ .nodePortHttps }}
  selector:
    app.kubernetes.io/name: keycloak
---
{{- end }}
